
export const metadata = {
  title: 'Paranomal Games',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      

      <div>
        {children}
      </div>
    </div>
  );
}

